version: '3.4'
services:
  api:
    image: {{runnable}}
  db:
    image: mysql:5.7.17
    ports:
      - 3316:3306
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "datastore"
    healthcheck:
      test: ["CMD", "echo", "test"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /tmp/datastore:/var/lib/mysql
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /tmp/redis:/data
    environment:
      DUMMY: "dummy"
    healthcheck:
      test: ["CMD", "echo", "test"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  mock:
    image: nginx
    ports:
      - 80
    healthcheck:
      test: ["CMD", "echo", "test"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
